// frontend/src/modules/container/components/MonitorTimeRange.vue
<script setup lang="ts">
import type { MonitorRange } from '@/modules/container/types/monitor'
import { RANGE_STEP_MAP } from '@/modules/container/types/monitor'

const props = defineProps<{
  value: MonitorRange
}>()

const emit = defineEmits<{
  'update:value': [range: MonitorRange]
}>()

const options: { value: MonitorRange; label: string }[] = Object.entries(RANGE_STEP_MAP).map(([value, config]) => ({
  value: value as MonitorRange,
  label: config.label,
}))
</script>

<template>
  <n-space align="center" style="margin-bottom: 12px">
    <n-radio-group :value="value" @update:value="(v: MonitorRange) => emit('update:value', v)">
      <n-radio-button
        v-for="opt in options"
        :key="opt.value"
        :value="opt.value"
        :label="opt.label"
      />
    </n-radio-group>
    <slot />
  </n-space>
</template>

// frontend/src/modules/container/components/MonitorTimeRange.tsx
import { type ReactNode } from 'react'
import { RANGE_STEP_MAP, type MonitorRange } from '@/modules/container/types/monitor'
import { cn } from '@/lib/utils'

const ranges = Object.keys(RANGE_STEP_MAP) as MonitorRange[]

export function MonitorTimeRange({
  value,
  onChange,
  extra,
}: {
  value: MonitorRange
  onChange: (value: MonitorRange) => void
  extra?: ReactNode
}) {
  return (
    <div className="flex flex-wrap items-center justify-between gap-3">
      <div className="flex gap-1">
        {ranges.map((range) => (
          <button
            key={range}
            type="button"
            className={cn(
              'h-8 rounded-md px-3 text-sm',
              value === range ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground',
            )}
            onClick={() => onChange(range)}
          >
            {RANGE_STEP_MAP[range].label}
          </button>
        ))}
      </div>
      {extra}
    </div>
  )
}
