// frontend/src/AppShell.vue
<script setup lang="ts">
import { BookOpen, LayoutDashboard, Moon, Search, Settings, Sun, Users, UserRound } from '@lucide/vue'
import { useAuthStore } from '@/modules/user/stores/auth'
import MessageBell from '@/modules/user/components/MessageBell.vue'
import ProductSwitcher from '@/shared/console/ProductSwitcher.vue'
import SecondaryTabs from '@/shared/console/SecondaryTabs.vue'
import { resolveActiveTab } from '@/shared/console/tabs'
import { useHelpLinks } from '@/modules/pm/composables/useWorkbench'
import { useConsoleTheme } from '@/shared/console/useConsoleTheme'
import { useMessage } from 'naive-ui'
import type { DropdownDividerOption, DropdownOption } from 'naive-ui'

const auth = useAuthStore()
const router = useRouter()
const route = useRoute()
const message = useMessage()
const messageBellRef = ref<InstanceType<typeof MessageBell> | null>(null)
const helpLinks = useHelpLinks()
const { isDark, toggle: toggleTheme } = useConsoleTheme()
const keyword = ref('')

onMounted(() => {
  if (!auth.isLoggedIn) return
  if (!auth.user) {
    void auth.fetchMe()
  } else {
    void auth.fetchMyTenants()
  }
})

/**
 * 二级 Tab 只属于当前产品：工作台、用户中心、账号设置等平台页不展示 Tab
 */
const showTabs = computed(
  () => auth.isLoggedIn && !route.meta.public && resolveActiveTab(route.path) !== null,
)

const isConsoleActive = computed(() => route.path === '/workbench')

const showTenantSwitcher = computed(() => auth.myTenants.length > 1)

const tenantOptions = computed(() =>
  auth.myTenants.map((t) => ({
    label: t.name,
    key: String(t.id),
    disabled: String(t.id) === String(auth.activeTenantId),
  })),
)

const userMenuOptions = computed<Array<DropdownOption | DropdownDividerOption>>(() => [
  { label: '账号设置', key: 'settings' },
  { type: 'divider', key: 'd1' },
  { label: '退出登录', key: 'logout' },
])

const avatarText = computed(() => {
  const name = auth.user?.displayName || auth.user?.username || '?'
  return name.slice(0, 1).toUpperCase()
})

async function onSwitchTenant(tenantId: string | number) {
  try {
    await auth.switchTenant(tenantId)
    message.success('已切换租户')
    messageBellRef.value?.refresh()
    await router.replace('/workbench')
  } catch (e) {
    message.error(e instanceof Error ? e.message : '切换租户失败')
  }
}

function onUserMenu(key: string | number) {
  if (key === 'settings') void router.push('/user/settings')
  else if (key === 'logout') logout()
}

function goUserCenter() {
  void router.push('/user/accounts')
}

function onSearch() {
  const value = keyword.value.trim()
  if (!value) return
  void router.push({ path: '/pm/projects', query: { keyword: value } })
}

function logout() {
  void auth.logout()
}
</script>

<template>
  <n-layout style="min-height: 100vh">
    <n-layout-header bordered class="top-bar">
      <!-- 左区：Logo + 控制台 + 产品目录下拉 -->
      <div class="top-left">
        <router-link to="/workbench" class="brand">
          <span class="brand-logo">H</span>
          <span class="brand-name">HFWAS DevOps</span>
        </router-link>
        <n-button
          v-if="auth.isLoggedIn"
          :class="{ 'console-active': isConsoleActive }"
          quaternary
          size="small"
          class="console-btn"
          @click="router.push('/workbench')"
        >
          <template #icon><LayoutDashboard :size="15" /></template>
          控制台
        </n-button>
        <ProductSwitcher v-if="auth.isLoggedIn" />
      </div>

      <!-- 中区：全局搜索 -->
      <div class="top-center">
        <n-input
          v-if="auth.isLoggedIn"
          v-model:value="keyword"
          placeholder="搜索项目名称或编码"
          clearable
          round
          size="small"
          @keyup.enter="onSearch"
        >
          <template #prefix><Search :size="14" /></template>
        </n-input>
      </div>

      <!-- 右区：文档 / 站内信 / 主题 / 用户中心 / 租户 / 用户 -->
      <div class="top-right">
        <template v-if="auth.isLoggedIn">
          <n-popover trigger="click" placement="bottom-end">
            <template #trigger>
              <n-button quaternary circle size="small" title="文档">
                <template #icon><BookOpen :size="16" /></template>
              </n-button>
            </template>
            <div class="help-list">
              <a v-for="link in helpLinks" :key="link.key" :href="link.href" class="help-item">
                {{ link.label }}
              </a>
            </div>
          </n-popover>

          <MessageBell ref="messageBellRef" />

          <n-button
            quaternary
            circle
            size="small"
            :title="isDark ? '切换为浅色' : '切换为深色'"
            @click="toggleTheme"
          >
            <template #icon>
              <Sun v-if="isDark" :size="16" />
              <Moon v-else :size="16" />
            </template>
          </n-button>

          <n-button
            v-if="auth.isAdmin"
            size="small"
            quaternary
            class="uc-entry"
            title="用户中心"
            @click="goUserCenter"
          >
            <template #icon><Users :size="15" /></template>
            用户中心
          </n-button>

          <n-dropdown
            v-if="showTenantSwitcher"
            trigger="click"
            :options="tenantOptions"
            :disabled="auth.switchingTenant"
            @select="onSwitchTenant"
          >
            <n-button size="small" quaternary :loading="auth.switchingTenant">
              <template #icon><Settings :size="14" /></template>
              {{ auth.activeTenantName ?? '选择租户' }}
            </n-button>
          </n-dropdown>
          <n-text v-else-if="auth.activeTenantName" depth="3" class="tenant-text">
            {{ auth.activeTenantName }}
          </n-text>

          <n-dropdown trigger="click" :options="userMenuOptions" @select="onUserMenu">
            <button type="button" class="user-trigger">
              <n-avatar round :size="26" class="user-avatar">{{ avatarText }}</n-avatar>
              <span class="user-name">{{ auth.user?.displayName ?? auth.user?.username }}</span>
            </button>
          </n-dropdown>
        </template>
        <router-link v-else to="/user/login" class="login-link">
          <UserRound :size="14" />
          登录
        </router-link>
      </div>
    </n-layout-header>

    <!-- 二级 Tab 导航 -->
    <SecondaryTabs v-if="showTabs" />

    <n-layout-content>
      <router-view :key="String(auth.activeTenantId ?? '') + '-' + auth.tenantVersion" />
    </n-layout-content>
  </n-layout>
</template>

<style scoped>
.top-bar {
  display: flex;
  align-items: center;
  gap: 16px;
  height: 56px;
  padding: 0 24px;
}

.top-left {
  display: flex;
  flex-shrink: 0;
  align-items: center;
  gap: 12px;
}

.brand {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: inherit;
  text-decoration: none;
}

.brand-logo {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 26px;
  height: 26px;
  border-radius: 7px;
  background: linear-gradient(135deg, #4098fc, #7c3aed);
  color: #fff;
  font-size: 14px;
  font-weight: 700;
}

.brand-name {
  font-size: 15px;
  font-weight: 600;
}

.console-btn {
  font-size: 13px;
  color: var(--wb-muted, #6b7280);
}

.console-btn:hover {
  color: #2d80e6;
}

.console-btn.console-active {
  color: #2d80e6;
  font-weight: 500;
}

.top-center {
  flex: 1;
  display: flex;
  justify-content: center;
  min-width: 0;
}

.top-center :deep(.n-input) {
  max-width: 420px;
}

.top-right {
  display: flex;
  flex-shrink: 0;
  align-items: center;
  gap: 10px;
}

.tenant-text {
  font-size: 13px;
}

.uc-entry {
  font-size: 13px;
}

.user-trigger {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 3px 6px;
  border: none;
  border-radius: 999px;
  background: transparent;
  font: inherit;
  font-size: 13px;
  color: inherit;
  cursor: pointer;
}

.user-trigger:hover {
  background: rgba(64, 152, 252, 0.1);
}

.user-avatar {
  background: #2d80e6;
  color: #fff;
  font-size: 12px;
  font-weight: 600;
}

.user-name {
  max-width: 120px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.login-link {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 13px;
}

.help-list {
  display: flex;
  flex-direction: column;
  min-width: 140px;
}

.help-item {
  padding: 6px 4px;
  font-size: 13px;
}
</style>

// frontend/src/components/console/AppShell.tsx
import { useEffect, useState } from 'react'
import { LayoutDashboard, Moon, Search, Settings, Sun, Users } from 'lucide-react'
import { Link, Outlet, useLocation, useNavigate } from 'react-router'
import { toast } from 'sonner'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import { ProductSwitcher } from '@/components/console/ProductSwitcher'
import { getConsoleTheme, subscribeConsoleTheme, toggleConsoleTheme } from '@/shared/console/useConsoleTheme'
import { useAuthStore } from '@/stores/auth'

export function AppShell() {
  const navigate = useNavigate()
  const location = useLocation()
  const user = useAuthStore((s) => s.user)
  const myTenants = useAuthStore((s) => s.myTenants)
  const activeTenantId = useAuthStore((s) => s.activeTenantId)
  const activeTenantName = useAuthStore((s) => s.activeTenantName)
  const isLoggedIn = useAuthStore((s) => s.isLoggedIn())
  const isAdmin = useAuthStore((s) => s.isAdmin())
  const fetchMe = useAuthStore((s) => s.fetchMe)
  const fetchMyTenants = useAuthStore((s) => s.fetchMyTenants)
  const switchTenant = useAuthStore((s) => s.switchTenant)
  const logout = useAuthStore((s) => s.logout)
  const [keyword, setKeyword] = useState('')
  const [dark, setDark] = useState(getConsoleTheme)

  useEffect(() => subscribeConsoleTheme(() => setDark(getConsoleTheme())), [])

  useEffect(() => {
    if (!isLoggedIn) return
    if (!user) {
      void fetchMe()
    } else {
      void fetchMyTenants()
    }
  }, [fetchMe, fetchMyTenants, isLoggedIn, user])

  const avatarText = (user?.displayName || user?.username || '?').slice(0, 1).toUpperCase()
  const consoleActive = location.pathname === '/workbench'

  async function onSwitchTenant(tenantId: string) {
    try {
      await switchTenant(tenantId)
      toast.success('已切换租户')
      await navigate('/workbench')
    } catch (e) {
      toast.error(e instanceof Error ? e.message : '切换租户失败')
    }
  }

  function onSearch() {
    const value = keyword.trim()
    if (!value) return
    void navigate({ pathname: '/pm/projects', search: `?keyword=${encodeURIComponent(value)}` })
  }

  return (
    <div className="flex min-h-svh flex-col bg-muted/40">
      <header className="sticky top-0 z-40 flex h-14 items-center gap-3 border-b bg-background px-4">
        <div className="flex items-center gap-2">
          <Link to="/workbench" className="flex items-center gap-2 text-foreground">
            <span className="flex size-7 items-center justify-center rounded-md bg-primary text-sm font-semibold text-primary-foreground">
              H
            </span>
            <span className="text-sm font-semibold">HFWAS DevOps</span>
          </Link>
          {isLoggedIn && (
            <Button
              variant={consoleActive ? 'secondary' : 'ghost'}
              size="sm"
              onClick={() => void navigate('/workbench')}
            >
              <LayoutDashboard />
              控制台
            </Button>
          )}
          {isLoggedIn && <ProductSwitcher />}
        </div>

        <form
          className="mx-auto hidden w-full max-w-md md:block"
          onSubmit={(event) => {
            event.preventDefault()
            onSearch()
          }}
        >
          {isLoggedIn && (
            <div className="relative">
              <Search className="pointer-events-none absolute top-1/2 left-2.5 size-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                value={keyword}
                onChange={(event) => setKeyword(event.target.value)}
                placeholder="搜索项目名称或编码"
                className="pl-8"
              />
            </div>
          )}
        </form>

        {isLoggedIn && (
          <div className="ml-auto flex items-center gap-2">
            {myTenants.length > 1 && (
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" size="sm">
                    {activeTenantName || '租户'}
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  {myTenants.map((tenant) => (
                    <DropdownMenuItem
                      key={String(tenant.id)}
                      disabled={String(tenant.id) === String(activeTenantId)}
                      onSelect={() => void onSwitchTenant(String(tenant.id))}
                    >
                      {tenant.name}
                    </DropdownMenuItem>
                  ))}
                </DropdownMenuContent>
              </DropdownMenu>
            )}
            <Button variant="ghost" size="icon" onClick={toggleConsoleTheme} aria-label="切换主题">
              {dark ? <Sun /> : <Moon />}
            </Button>
            {isAdmin && (
              <Button variant="ghost" size="icon" aria-label="用户中心" onClick={() => void navigate('/user/accounts')}>
                <Users />
              </Button>
            )}
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <button type="button" className="rounded-full">
                  <Avatar>
                    <AvatarFallback>{avatarText}</AvatarFallback>
                  </Avatar>
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onSelect={() => void navigate('/user/settings')}>
                  <Settings />
                  账号设置
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem onSelect={() => void logout()}>退出登录</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        )}
      </header>
      <main className="min-h-0 flex-1">
        <Outlet />
      </main>
    </div>
  )
}
